@startuml

(*) --> "Клиент заходит на сайт"
--> [Просмотрев информацию об организации] "Принял решение записаться на приём"
--> "Нажал на кнопку записи на приём"
if "Пользователь аутентифицирован" then
    --> [Да] "Осуществляется переход на страницу записи"
    if "Есть необходимая услуга" then
        --> [Да] "Выбор услуги" 
        --> "Переход на страницу выбора даты"
        if "Есть необходимая свободная дата для записи" then
            --> [Да] "Выбор даты для записи"
            --> "Переход на страницу выбора времени приёма" 
            if "Есть подходящее время" then
                --> [Да] "Выбор времени записи"
                --> "Заполнение личных данных"
                --> (*)
            else
                --> [Нет] (*)
            endif
        else
            --> [Нет] (*)
        endif
    else
        --> [Нет] (*)
    endif
else
    --> [Нет] "Форма аутентификации по номеру телефона" 
    if "Успешная аутентификация" then
        --> [Да] "Осуществляется переход на страницу записи"
    else
        --> [Нет] "Форма аутентификации по номеру телефона"
    endif
endif

@enduml