@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

' LAYOUT_WITH_LEGEND

title Диаграмма контекста для интернет приложения медицинской организации

Person(customer, "Пользователь", "Пользователь сайта")
Person(appointment_admin, Администратор Записей, "Администратор Записей")
Person(content_admin, "Администратор Контента", "Администратор Контента")
System(site, "Интернет приложение медицинской организации", "Позволяет пользователям просмотреть информацию об организации и записаться на приём к врачу")
System_Ext(SMS, "Аутентификация пользователя в записи на приём", "Посылает SMS уведомления пользователю")

Rel(customer, site, "Посещает")
Rel(content_admin, site, "Редактирует контент")
Rel(appointment_admin, site, "Редактирует и просматривает записи")
Rel(site, SMS, "Формирует сообщение")
@enduml
