@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

title Диаграмма контейнеров системы записи на приём

Person(customer, Пользователь, "Посетитель/Клиент")
Person(appointment_admin, Администратор Записей, "Администратор Записей")

System_Boundary(c1, "Система записи на приём") {
    Container(appointment_sys, "Форма записи", "C#, ASP.NET", "Позволяет клиенту заведения сделать запись")
    ContainerDb(database, "База Данных + API", "C#, SQLLite", "Тут хранится информация о сделанных записях и данных пользователей")
}

Rel(customer, appointment_sys, "Используя", "HTTPS")
Rel(appointment_admin, appointment_sys, "Просматривает записи", "CRM")
Rel(appointment_sys, database, "Пишет и читает", "async, JSON/HTTPS")

@enduml